name: prueba-s4n-haskell
version: 0.1.0.0
github: "dabliuw22/prueba-s4n-haskell"
license: BSD3
author: "Will Leyton"
maintainer: "wleylop22@gmail.com"
copyright: "2021 Will Leyton"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/dabliuw22/prueba-s4n-haskell#readme>

dependencies:
  - base >= 4.7 && < 5
  - hspec
  - exceptions
  - katip >= 0.1.0.0 && < 0.8.6.0
  - QuickCheck
  - envs
  - logs
  - files
  - core-s4n
  - delivery-domain
  - delivery-adapter
  - delivery-application
  - location-domain
  - location-adapter
  - location-application

library:
  source-dirs: src

executables:
  prueba-s4n-haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - prueba-s4n-haskell

tests:
  prueba-s4n-haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - prueba-s4n-haskell
